steps:
  - id: create-env
    name: "ubuntu"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "VITE_API_URL=$_VITE_API_URL" >> ./client/.env

  - id: build-image
    name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "eu.gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$SHORT_SHA", "."]

  - id: push-image
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "eu.gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$SHORT_SHA"]

  - id: deploy-image
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "${_IMAGE_NAME}",
        "--image",
        "eu.gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$SHORT_SHA",
        "--region",
        "europe-west2",
      ]

options:
  logging: CLOUD_LOGGING_ONLY
